---
layout: cv
title: Andrew Parrella's CV
---
# Andrew Parrella 
Geologist, College Student, GIS Analyst.

<div id="webaddress">
<a href="andrew.finholdt12@gmail.com">andrew.finholdt12@gmail.com</a>
| <a href="www.linkedin.com/in/andrew-luke-parrella-6604a02b9">My LinkedIn profile</a>
</div>


## Currently

Pursuing Geology Bachelor's Degree at Brigham Young University - Idaho

### Specialized in

Petroleum and Environmental Geology / GIS Data Collecting and Analyzing

### Research interests

Alternative Green Energy, Petroleum Sustainablity, Orogenic Events


## Education

`2006-2009, 2012-2013`
__International School of Alphaville, Brazil__

`2009-2012`
__The American School of Belo Horizonte, Brazil__

`2013-2014, 2015-2017`
__Escola Fernao Gaivota - Maple Bear Alphaville, Brazil__

`2014-2015`
__Colégio Positivo, Brazil__

`2017-2018`
__Legacy Preparatory Academy, Utah, USA__

`2018-2021`
__Graded - The American School of São Paulo, Brazil__

`2024-now`
__Brigham Young University-Idaho, USA__


## Occupation

`2024`
__Pre-Arrival Mentor - BYUI__

`2024-now`
__Pre-Arrival Mentor Lead - BYUI__

`2024-2025`
__Geology 111 Teacher's Assistant - BYUI__



<!-- ### Footer

Last updated: April 2025 -->